const fs = require('fs');
const path = require('path');
const env = require('../config/env');
const logger = require('../utils/logger');

class ProjectScaffolder {
  constructor() {
    this.baseDir = env.GENERATED_PROJECTS_DIR;
  }

  getProjectDir(projectId) {
    return path.join(this.baseDir, projectId.toString());
  }

  async writeProjectToDisk(projectId, files) {
    const projectDir = this.getProjectDir(projectId);

    // Create base directory
    fs.mkdirSync(projectDir, { recursive: true });

    for (const file of files) {
      const filePath = path.join(projectDir, file.path);
      const dir = path.dirname(filePath);
      fs.mkdirSync(dir, { recursive: true });
      fs.writeFileSync(filePath, file.content, 'utf-8');
    }

    logger.info(`Project written to disk: ${projectDir} (${files.length} files)`);
    return projectDir;
  }

  createScaffoldFiles(project) {
    const files = [];

    // package.json
    files.push({
      path: 'package.json',
      content: JSON.stringify({
        name: this.toKebabCase(project.name),
        version: '1.0.0',
        private: true,
        scripts: {
          start: 'node src/index.js',
          dev: 'node --watch src/index.js',
          seed: 'node src/seed.js'
        },
        dependencies: {
          express: '^4.18.2',
          cors: '^2.8.5',
          mongoose: '^8.1.1',
          dotenv: '^16.4.1'
        }
      }, null, 2),
      language: 'json',
      generatedBy: 'template',
      module: 'scaffold'
    });

    // .env
    files.push({
      path: '.env',
      content: `PORT=3000\nMONGODB_URI=mongodb://localhost:27017/${this.toKebabCase(project.name)}\nNODE_ENV=production\n`,
      language: 'env',
      generatedBy: 'template',
      module: 'scaffold'
    });

    // .gitignore
    files.push({
      path: '.gitignore',
      content: 'node_modules/\n.env\n*.log\ndist/\n',
      language: 'text',
      generatedBy: 'template',
      module: 'scaffold'
    });

    // README
    files.push({
      path: 'README.md',
      content: `# ${project.name}\n\n${project.description || 'Generated application'}\n\n## Setup\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n\n## API Endpoints\n\nAll endpoints are available under \`/api\`.\n\nGenerated by ERP Builder Platform.\n`,
      language: 'markdown',
      generatedBy: 'template',
      module: 'scaffold'
    });

    return files;
  }

  createFrontendScaffold(project) {
    const files = [];

    // Frontend package.json
    files.push({
      path: 'client/package.json',
      content: JSON.stringify({
        name: `${this.toKebabCase(project.name)}-client`,
        private: true,
        version: '1.0.0',
        type: 'module',
        scripts: {
          dev: 'vite',
          build: 'vite build',
          preview: 'vite preview'
        },
        dependencies: {
          react: '^18.2.0',
          'react-dom': '^18.2.0',
          'react-router-dom': '^6.22.0',
          axios: '^1.6.5'
        },
        devDependencies: {
          '@vitejs/plugin-react': '^4.2.1',
          vite: '^5.0.12',
          tailwindcss: '^3.4.1',
          postcss: '^8.4.33',
          autoprefixer: '^10.4.17'
        }
      }, null, 2),
      language: 'json',
      generatedBy: 'template',
      module: 'scaffold'
    });

    // Vite config
    files.push({
      path: 'client/vite.config.js',
      content: `import { defineConfig } from 'vite';\nimport react from '@vitejs/plugin-react';\n\nexport default defineConfig({\n  plugins: [react()],\n  server: {\n    proxy: {\n      '/api': 'http://localhost:3000'\n    }\n  }\n});\n`,
      language: 'javascript',
      generatedBy: 'template',
      module: 'scaffold'
    });

    // Tailwind config
    files.push({
      path: 'client/tailwind.config.js',
      content: `/** @type {import('tailwindcss').Config} */\nexport default {\n  content: ['./index.html', './src/**/*.{js,jsx}'],\n  theme: { extend: {} },\n  plugins: []\n};\n`,
      language: 'javascript',
      generatedBy: 'template',
      module: 'scaffold'
    });

    // PostCSS config
    files.push({
      path: 'client/postcss.config.js',
      content: `export default {\n  plugins: {\n    tailwindcss: {},\n    autoprefixer: {}\n  }\n};\n`,
      language: 'javascript',
      generatedBy: 'template',
      module: 'scaffold'
    });

    // index.html
    files.push({
      path: 'client/index.html',
      content: `<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="UTF-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n  <title>${project.name}</title>\n</head>\n<body>\n  <div id="root"></div>\n  <script type="module" src="/src/main.jsx"></script>\n</body>\n</html>\n`,
      language: 'html',
      generatedBy: 'template',
      module: 'scaffold'
    });

    // main.jsx
    files.push({
      path: 'client/src/main.jsx',
      content: `import React from 'react';\nimport ReactDOM from 'react-dom/client';\nimport App from './App';\nimport './index.css';\n\nReactDOM.createRoot(document.getElementById('root')).render(\n  <React.StrictMode>\n    <App />\n  </React.StrictMode>\n);\n`,
      language: 'javascript',
      generatedBy: 'template',
      module: 'scaffold'
    });

    // index.css
    files.push({
      path: 'client/src/index.css',
      content: `@tailwind base;\n@tailwind components;\n@tailwind utilities;\n`,
      language: 'css',
      generatedBy: 'template',
      module: 'scaffold'
    });

    return files;
  }

  toKebabCase(str) {
    return str.replace(/([a-z])([A-Z])/g, '$1-$2').replace(/[\s_]+/g, '-').toLowerCase();
  }
}

module.exports = ProjectScaffolder;
